window.langEN = {
    greeting : "Hello",
    connexionMessage : "connection....",
    disconnectionMessage :"disconnection",
    master:"master",
    play:"playing",
    idle:"idle",
    textFindMe:"find the word which beginning by the following letter",
    textmastermind:"just the word mastermind(the same color can be used twice)",
       findMeWord :[
    "Tree",
    "Truck",
    "City",
    "Country",
    "Bug",
    "Sport",
    "Sportsman",
    "Sportswoman",
    "River",
    "Name of a boat",
    "Board game",
    "TV game",
    "Body part",
    "Russian word",
    "Spanish word",
    "French word",
    "German word",
    "TV series",
    "on your head",
    "Garment",
    "Car",
    "Book",
    "Firstname",
    "Comic",
    "Movie",
    "French town",
    "German town",
    "US town",
    "English town",
    "Spanish town",
    "Dishes",
    "French dishes",
    "English dishes",
    "Radio show",
    "French better then english :)",//ester egg
	"Flower",
	"King",
	"Queen",
	"Castel",
	"Video game",
	"Mange",
	"In your car",
	"At work",
	"Star",
	"Planet or Star",
	"Chemical element",
	"Motorcycle",
	"Actor",
	"Actress",
	"Island",
	"Drug",
	"Minister",
	"Comedian",
	"Writer",
	"Fictional character",
	"Male character",
	"Female character",
	"Scientist",
	"Battle",
	"Forest",
	"European capital",
	"Asian capitale",
	"African capital",
	"American capital",
	"Capital",
	"Mountain",
	"In the kitchen",
	"Computer brand",
	"Smartphone app",
	"Website",
	"Fruit",
	"Vegetal",
	"Parts of the pig",
	"Parts of the sheep",
	"Parts of the horse",
	"Parts of the cow",
	"Singer from the 80s",
	"Singer from the 70s",
	"Singer from the 90s",
	"Singer from the 2000s",
	"Songs from the 80s",
	"Songs from the 70s",
	"Songs from the 90s",
	"Songs from the 2000s",
	"At breakfast",
	"On a plane",
	"European countries",
	"African countries",
	"Asian countries",
	"Oceanian countries",
	"American countries",
	"Poet",
	"Singer",
	"Rock band",
	"Animal",
	"Bread of dog",
	"Spice",
	"Brand of a car",
	"Video games",
	"Jewerly",
	"In a makeup bag",
	"in the bedroom",
	"In the kitchen"
    ]
};